apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: my-nginx-values
  namespace: flux-blue
spec:
  interval: 5m
  releaseName: my-nginx
  chart:
    spec:
      chart: nginx     
      sourceRef:
        kind: HelmRepository
        name: my-chart-repo  
        namespace: flux-blue
  install:
    remediation:
      retries: 3
  values:
    replicaCount: 2

