apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: my-nginx-values
  namespace: flux-blue
spec:
  interval: 5m
  chart:
    spec:
      version: ">=1.0.0"
  values:
    replicaCount: 3
